MALE_BODY_TRAIT_OPTIONS = {
    "build_type": [
        "skinny and bony",
        "lean and wiry",
        "athletic and cut",
        "thick and powerful",
        "heavy and massive",
    ],
    "muscle_definition": [
        "skinny with little muscle",
        "soft and undefined",
        "toned and defined",
        "heavily muscled",
        "freakishly jacked",
    ],
    "body_fat_pct": [
        "shredded 8-12%",
        "athletic 12-18%",
        "average 18-25%",
        "heavy 25-35%",
        "obese 35-45%",
    ],
    "shoulder_width": [
        "narrow and bony",
        "narrow",
        "average",
        "broad",
        "very broad",
    ],
    "chest_build": [
        "sunken and narrow",
        "soft and flat",
        "defined pecs",
        "barrel-chested",
        "massive slabs",
    ],
    "waist": [
        "skinny and narrow",
        "narrow v-taper",
        "medium",
        "soft belly",
        "big gut",
    ],
    "face_shape": [
        "sharp angular",
        "square jaw",
        "broad and flat",
        "gaunt hollow",
        "rugged weathered",
    ],
    "eye_expression": [
        "cold dead",
        "predatory",
        "calculating",
        "wild unhinged",
        "focused intense",
    ],
    "facial_hair": [
        "clean-shaven",
        "stubble",
        "full beard",
        "mustache",
        "goatee",
    ],
}

MALE_BODY_PROFILES = {
    "Skinny": {
        "body_fat_pct": ["shredded 8-12%", "athletic 12-18%"],
        "muscle_definition": ["skinny with little muscle", "soft and undefined"],
        "shoulder_width": ["narrow and bony", "narrow"],
        "chest_build": ["sunken and narrow", "soft and flat"],
        "build_type": ["skinny and bony"],
        "waist": ["skinny and narrow"],
    },
    "Wiry": {
        "body_fat_pct": ["shredded 8-12%", "athletic 12-18%"],
        "muscle_definition": ["skinny with little muscle", "toned and defined"],
        "shoulder_width": ["narrow", "average"],
        "chest_build": ["soft and flat", "defined pecs"],
        "build_type": ["lean and wiry"],
        "waist": ["skinny and narrow", "narrow v-taper"],
    },
    "Athletic": {
        "body_fat_pct": ["athletic 12-18%", "average 18-25%"],
        "muscle_definition": ["toned and defined", "heavily muscled"],
        "shoulder_width": ["average", "broad"],
        "chest_build": ["defined pecs", "barrel-chested"],
        "build_type": ["athletic and cut"],
        "waist": ["narrow v-taper", "medium"],
    },
    "Muscular": {
        "body_fat_pct": ["athletic 12-18%", "average 18-25%"],
        "muscle_definition": ["heavily muscled", "freakishly jacked"],
        "shoulder_width": ["broad", "very broad"],
        "chest_build": ["barrel-chested", "massive slabs"],
        "build_type": ["thick and powerful"],
        "waist": ["narrow v-taper", "medium"],
    },
    "Stocky": {
        "body_fat_pct": ["average 18-25%", "heavy 25-35%"],
        "muscle_definition": ["soft and undefined", "toned and defined"],
        "shoulder_width": ["average", "broad"],
        "chest_build": ["soft and flat", "barrel-chested"],
        "build_type": ["thick and powerful", "athletic and cut"],
        "waist": ["medium", "soft belly"],
    },
    "Heavy": {
        "body_fat_pct": ["heavy 25-35%", "obese 35-45%"],
        "muscle_definition": ["soft and undefined", "heavily muscled"],
        "shoulder_width": ["broad", "very broad"],
        "chest_build": ["barrel-chested", "massive slabs"],
        "build_type": ["heavy and massive"],
        "waist": ["soft belly", "big gut"],
    },
    "Massive": {
        "body_fat_pct": ["average 18-25%", "heavy 25-35%"],
        "muscle_definition": ["heavily muscled", "freakishly jacked"],
        "shoulder_width": ["broad", "very broad"],
        "chest_build": ["barrel-chested", "massive slabs"],
        "build_type": ["heavy and massive", "thick and powerful"],
        "waist": ["medium", "soft belly"],
    },
}

MALE_ARCHETYPE_BODY_PROFILE_WEIGHTS = {
    "The Brute": {
        "Skinny": 0,
        "Wiry": 5,
        "Athletic": 10,
        "Muscular": 20,
        "Stocky": 15,
        "Heavy": 25,
        "Massive": 25,
    },
    "The Veteran": {
        "Skinny": 5,
        "Wiry": 15,
        "Athletic": 25,
        "Muscular": 15,
        "Stocky": 25,
        "Heavy": 10,
        "Massive": 5,
    },
    "The Monster": {
        "Skinny": 0,
        "Wiry": 0,
        "Athletic": 5,
        "Muscular": 15,
        "Stocky": 5,
        "Heavy": 25,
        "Massive": 50,
    },
    "The Technician": {
        "Skinny": 10,
        "Wiry": 30,
        "Athletic": 30,
        "Muscular": 15,
        "Stocky": 10,
        "Heavy": 5,
        "Massive": 0,
    },
    "The Wildcard": {
        "Skinny": 15,
        "Wiry": 15,
        "Athletic": 20,
        "Muscular": 10,
        "Stocky": 15,
        "Heavy": 15,
        "Massive": 10,
    },
    "The Mystic": {
        "Skinny": 20,
        "Wiry": 30,
        "Athletic": 25,
        "Muscular": 10,
        "Stocky": 10,
        "Heavy": 5,
        "Massive": 0,
    },
    "The Prodigy": {
        "Skinny": 15,
        "Wiry": 25,
        "Athletic": 35,
        "Muscular": 15,
        "Stocky": 5,
        "Heavy": 5,
        "Massive": 0,
    },
    "The Experiment": {
        "Skinny": 5,
        "Wiry": 10,
        "Athletic": 15,
        "Muscular": 20,
        "Stocky": 10,
        "Heavy": 20,
        "Massive": 20,
    },
}

MALE_ARCHETYPE_HEIGHT_RANGES = {
    "The Brute": (72, 78),
    "The Veteran": (69, 75),
    "The Monster": (74, 80),
    "The Technician": (68, 74),
    "The Wildcard": (68, 75),
    "The Mystic": (69, 75),
    "The Prodigy": (69, 74),
    "The Experiment": (70, 77),
}

MALE_ARCHETYPE_BODY_WEIGHTS = {
    "The Brute": {
        "muscle_definition": {
            "skinny with little muscle": 0,
            "soft and undefined": 10,
            "toned and defined": 15,
            "heavily muscled": 35,
            "freakishly jacked": 40,
        },
        "body_fat_pct": {
            "shredded 8-12%": 5,
            "athletic 12-18%": 10,
            "average 18-25%": 30,
            "heavy 25-35%": 35,
            "obese 35-45%": 20,
        },
        "shoulder_width": {
            "narrow and bony": 0,
            "narrow": 5,
            "average": 15,
            "broad": 35,
            "very broad": 45,
        },
        "chest_build": {
            "sunken and narrow": 0,
            "soft and flat": 5,
            "defined pecs": 15,
            "barrel-chested": 40,
            "massive slabs": 40,
        },
        "facial_hair": {
            "clean-shaven": 10,
            "stubble": 30,
            "full beard": 35,
            "mustache": 10,
            "goatee": 15,
        },
        "eye_expression": {
            "cold dead": 20,
            "predatory": 35,
            "calculating": 5,
            "wild unhinged": 30,
            "focused intense": 10,
        },
        "waist": {
            "skinny and narrow": 0,
            "narrow v-taper": 5,
            "medium": 20,
            "soft belly": 40,
            "big gut": 35,
        },
    },
    "The Veteran": {
        "muscle_definition": {
            "skinny with little muscle": 5,
            "soft and undefined": 20,
            "toned and defined": 35,
            "heavily muscled": 30,
            "freakishly jacked": 10,
        },
        "body_fat_pct": {
            "shredded 8-12%": 5,
            "athletic 12-18%": 20,
            "average 18-25%": 40,
            "heavy 25-35%": 25,
            "obese 35-45%": 10,
        },
        "shoulder_width": {
            "narrow and bony": 5,
            "narrow": 15,
            "average": 30,
            "broad": 35,
            "very broad": 15,
        },
        "chest_build": {
            "sunken and narrow": 5,
            "soft and flat": 15,
            "defined pecs": 35,
            "barrel-chested": 35,
            "massive slabs": 10,
        },
        "facial_hair": {
            "clean-shaven": 15,
            "stubble": 35,
            "full beard": 25,
            "mustache": 15,
            "goatee": 10,
        },
        "eye_expression": {
            "cold dead": 15,
            "predatory": 20,
            "calculating": 35,
            "wild unhinged": 5,
            "focused intense": 25,
        },
        "waist": {
            "skinny and narrow": 5,
            "narrow v-taper": 10,
            "medium": 35,
            "soft belly": 35,
            "big gut": 15,
        },
    },
    "The Monster": {
        "muscle_definition": {
            "skinny with little muscle": 0,
            "soft and undefined": 10,
            "toned and defined": 10,
            "heavily muscled": 35,
            "freakishly jacked": 45,
        },
        "body_fat_pct": {
            "shredded 8-12%": 5,
            "athletic 12-18%": 10,
            "average 18-25%": 25,
            "heavy 25-35%": 35,
            "obese 35-45%": 25,
        },
        "shoulder_width": {
            "narrow and bony": 0,
            "narrow": 0,
            "average": 5,
            "broad": 30,
            "very broad": 65,
        },
        "chest_build": {
            "sunken and narrow": 0,
            "soft and flat": 0,
            "defined pecs": 10,
            "barrel-chested": 35,
            "massive slabs": 55,
        },
        "facial_hair": {
            "clean-shaven": 20,
            "stubble": 20,
            "full beard": 35,
            "mustache": 10,
            "goatee": 15,
        },
        "eye_expression": {
            "cold dead": 30,
            "predatory": 30,
            "calculating": 5,
            "wild unhinged": 30,
            "focused intense": 5,
        },
        "waist": {
            "skinny and narrow": 0,
            "narrow v-taper": 0,
            "medium": 15,
            "soft belly": 40,
            "big gut": 45,
        },
    },
    "The Technician": {
        "muscle_definition": {
            "skinny with little muscle": 10,
            "soft and undefined": 15,
            "toned and defined": 45,
            "heavily muscled": 25,
            "freakishly jacked": 5,
        },
        "body_fat_pct": {
            "shredded 8-12%": 15,
            "athletic 12-18%": 40,
            "average 18-25%": 30,
            "heavy 25-35%": 10,
            "obese 35-45%": 5,
        },
        "shoulder_width": {
            "narrow and bony": 10,
            "narrow": 25,
            "average": 35,
            "broad": 25,
            "very broad": 5,
        },
        "chest_build": {
            "sunken and narrow": 10,
            "soft and flat": 20,
            "defined pecs": 40,
            "barrel-chested": 25,
            "massive slabs": 5,
        },
        "facial_hair": {
            "clean-shaven": 35,
            "stubble": 30,
            "full beard": 10,
            "mustache": 10,
            "goatee": 15,
        },
        "eye_expression": {
            "cold dead": 10,
            "predatory": 10,
            "calculating": 45,
            "wild unhinged": 5,
            "focused intense": 30,
        },
        "waist": {
            "skinny and narrow": 15,
            "narrow v-taper": 25,
            "medium": 35,
            "soft belly": 20,
            "big gut": 5,
        },
    },
    "The Wildcard": {
        "muscle_definition": {
            "skinny with little muscle": 15,
            "soft and undefined": 20,
            "toned and defined": 25,
            "heavily muscled": 25,
            "freakishly jacked": 15,
        },
        "body_fat_pct": {
            "shredded 8-12%": 10,
            "athletic 12-18%": 20,
            "average 18-25%": 30,
            "heavy 25-35%": 25,
            "obese 35-45%": 15,
        },
        "shoulder_width": {
            "narrow and bony": 10,
            "narrow": 20,
            "average": 30,
            "broad": 25,
            "very broad": 15,
        },
        "chest_build": {
            "sunken and narrow": 10,
            "soft and flat": 20,
            "defined pecs": 30,
            "barrel-chested": 25,
            "massive slabs": 15,
        },
        "facial_hair": {
            "clean-shaven": 20,
            "stubble": 25,
            "full beard": 20,
            "mustache": 15,
            "goatee": 20,
        },
        "eye_expression": {
            "cold dead": 10,
            "predatory": 15,
            "calculating": 10,
            "wild unhinged": 45,
            "focused intense": 20,
        },
        "waist": {
            "skinny and narrow": 10,
            "narrow v-taper": 15,
            "medium": 30,
            "soft belly": 25,
            "big gut": 20,
        },
    },
    "The Mystic": {
        "muscle_definition": {
            "skinny with little muscle": 20,
            "soft and undefined": 15,
            "toned and defined": 35,
            "heavily muscled": 25,
            "freakishly jacked": 5,
        },
        "body_fat_pct": {
            "shredded 8-12%": 20,
            "athletic 12-18%": 35,
            "average 18-25%": 30,
            "heavy 25-35%": 10,
            "obese 35-45%": 5,
        },
        "shoulder_width": {
            "narrow and bony": 15,
            "narrow": 25,
            "average": 30,
            "broad": 25,
            "very broad": 5,
        },
        "chest_build": {
            "sunken and narrow": 15,
            "soft and flat": 20,
            "defined pecs": 35,
            "barrel-chested": 25,
            "massive slabs": 5,
        },
        "facial_hair": {
            "clean-shaven": 25,
            "stubble": 20,
            "full beard": 30,
            "mustache": 10,
            "goatee": 15,
        },
        "eye_expression": {
            "cold dead": 15,
            "predatory": 10,
            "calculating": 30,
            "wild unhinged": 10,
            "focused intense": 35,
        },
        "waist": {
            "skinny and narrow": 20,
            "narrow v-taper": 25,
            "medium": 30,
            "soft belly": 20,
            "big gut": 5,
        },
    },
    "The Prodigy": {
        "muscle_definition": {
            "skinny with little muscle": 15,
            "soft and undefined": 10,
            "toned and defined": 45,
            "heavily muscled": 25,
            "freakishly jacked": 5,
        },
        "body_fat_pct": {
            "shredded 8-12%": 15,
            "athletic 12-18%": 40,
            "average 18-25%": 30,
            "heavy 25-35%": 10,
            "obese 35-45%": 5,
        },
        "shoulder_width": {
            "narrow and bony": 10,
            "narrow": 20,
            "average": 35,
            "broad": 30,
            "very broad": 5,
        },
        "chest_build": {
            "sunken and narrow": 10,
            "soft and flat": 15,
            "defined pecs": 40,
            "barrel-chested": 30,
            "massive slabs": 5,
        },
        "facial_hair": {
            "clean-shaven": 40,
            "stubble": 35,
            "full beard": 5,
            "mustache": 5,
            "goatee": 15,
        },
        "eye_expression": {
            "cold dead": 5,
            "predatory": 20,
            "calculating": 20,
            "wild unhinged": 15,
            "focused intense": 40,
        },
        "waist": {
            "skinny and narrow": 15,
            "narrow v-taper": 30,
            "medium": 35,
            "soft belly": 15,
            "big gut": 5,
        },
    },
    "The Experiment": {
        "muscle_definition": {
            "skinny with little muscle": 5,
            "soft and undefined": 15,
            "toned and defined": 20,
            "heavily muscled": 35,
            "freakishly jacked": 25,
        },
        "body_fat_pct": {
            "shredded 8-12%": 10,
            "athletic 12-18%": 15,
            "average 18-25%": 30,
            "heavy 25-35%": 30,
            "obese 35-45%": 15,
        },
        "shoulder_width": {
            "narrow and bony": 5,
            "narrow": 10,
            "average": 20,
            "broad": 35,
            "very broad": 30,
        },
        "chest_build": {
            "sunken and narrow": 5,
            "soft and flat": 10,
            "defined pecs": 20,
            "barrel-chested": 35,
            "massive slabs": 30,
        },
        "facial_hair": {
            "clean-shaven": 30,
            "stubble": 25,
            "full beard": 15,
            "mustache": 15,
            "goatee": 15,
        },
        "eye_expression": {
            "cold dead": 25,
            "predatory": 20,
            "calculating": 15,
            "wild unhinged": 25,
            "focused intense": 15,
        },
        "waist": {
            "skinny and narrow": 5,
            "narrow v-taper": 10,
            "medium": 25,
            "soft belly": 35,
            "big gut": 25,
        },
    },
}

BODY_TRAIT_OPTIONS = {
    "waist": ["narrow", "medium", "wide"],
    "abs_tone": [
        "soft with no definition",
        "slight definition",
        "toned and defined",
        "ripped and shredded",
    ],
    "body_fat_pct": ["lean 12-16%", "athletic 17-20%", "fit 21-24%", "soft 25-30%"],
    "butt_size": ["tiny tight", "medium round", "large thick", "very large prominent"],
    "face_shape": [
        "sharp angular",
        "soft round",
        "heart-shaped",
        "oval",
        "diamond",
    ],
    "eye_shape": [
        "almond",
        "round",
        "hooded",
        "doe",
        "cat-like",
    ],
    "nose_shape": [
        "small button",
        "straight narrow",
        "slightly upturned",
        "aquiline",
        "wide flat bridge",
        "delicate pointed",
    ],
    "lip_shape": [
        "thin precise",
        "full pouty",
        "wide generous",
        "cupid's bow",
        "naturally asymmetric",
    ],
    "brow_shape": [
        "straight low",
        "high arched",
        "thick natural",
        "thin sculpted",
        "heavy intense",
    ],
    "cheekbone": [
        "high prominent",
        "soft subtle",
        "wide flat",
        "hollow sculpted",
    ],
    "jawline": [
        "narrow pointed chin",
        "soft rounded",
        "defined angular",
        "wide strong",
        "delicate tapered",
    ],
    "eye_expression": [
        "cold",
        "predatory",
        "calculating",
        "contemptuous",
        "unblinking",
        "piercing",
        "narrowed",
        "half-lidded",
        "wide unblinking",
        "vacant",
        "knowing",
        "fierce",
        "smoldering",
        "wild",
        "glaring",
        "heavy-lidded",
        "focused",
    ],
    "makeup_level": ["bare-faced", "light", "moderate", "heavy"],
    "breast_size": [
        "tiny flat-chested",
        "small perky",
        "medium",
        "large heavy",
        "massive oversized",
    ],
    "nipple_size": ["small pert", "medium", "perky pointed", "large puffy"],
    "vulva_type": [
        "tucked pussy, small labia",
        "tasteful outer labia",
        "compact petite tight pussy",
        "visible labia minora peeking out",
    ],
}

BODY_PROFILES = {
    "Petite": {
        "body_fat_pct": ["lean 12-16%", "athletic 17-20%"],
        "abs_tone": ["slight definition", "toned and defined"],
        "waist": ["narrow"],
        "breast_size": ["tiny flat-chested", "small perky", "medium"],
        "butt_size": ["tiny tight", "medium round"],
    },
    "Slim": {
        "body_fat_pct": ["lean 12-16%", "athletic 17-20%"],
        "abs_tone": [
            "soft with no definition",
            "slight definition",
            "toned and defined",
        ],
        "waist": ["narrow", "medium"],
        "breast_size": ["tiny flat-chested", "small perky", "medium"],
        "butt_size": ["tiny tight", "medium round"],
    },
    "Athletic": {
        "body_fat_pct": ["lean 12-16%", "athletic 17-20%"],
        "abs_tone": ["toned and defined", "ripped and shredded"],
        "waist": ["narrow", "medium"],
        "breast_size": ["small perky", "medium", "large heavy"],
        "butt_size": ["medium round", "large thick"],
    },
    "Curvy": {
        "body_fat_pct": ["athletic 17-20%", "fit 21-24%"],
        "abs_tone": [
            "soft with no definition",
            "slight definition",
            "toned and defined",
        ],
        "waist": ["narrow", "medium"],
        "breast_size": ["medium", "large heavy", "massive oversized"],
        "butt_size": ["medium round", "large thick", "very large prominent"],
    },
}

ARCHETYPE_BODY_PROFILE_WEIGHTS = {
    "The Siren": {"Petite": 5, "Slim": 20, "Athletic": 20, "Curvy": 55},
    "The Witch": {"Petite": 20, "Slim": 30, "Athletic": 20, "Curvy": 30},
    "The Viper": {"Petite": 10, "Slim": 30, "Athletic": 42, "Curvy": 18},
    "The Prodigy": {"Petite": 35, "Slim": 33, "Athletic": 22, "Curvy": 10},
    "The Doll": {"Petite": 35, "Slim": 25, "Athletic": 12, "Curvy": 28},
    "The Huntress": {"Petite": 5, "Slim": 20, "Athletic": 50, "Curvy": 25},
    "The Empress": {"Petite": 5, "Slim": 15, "Athletic": 25, "Curvy": 55},
    "The Experiment": {"Petite": 15, "Slim": 22, "Athletic": 30, "Curvy": 33},
    "The Demon": {"Petite": 15, "Slim": 25, "Athletic": 20, "Curvy": 40},
    "The Assassin": {"Petite": 20, "Slim": 30, "Athletic": 40, "Curvy": 10},
    "The Nymph": {"Petite": 30, "Slim": 35, "Athletic": 15, "Curvy": 20},
}

MAKEUP_DESCRIPTIONS = {
    "bare-faced": "natural beauty, minimal or zero makeup",
    "light": "subtle enhancement, soft color accents",
    "moderate": "polished look, foundation, defined features, lipstick",
    "heavy": "full glam, dramatic makeup, contoured, bold lip",
}

ARCHETYPE_HEIGHT_RANGES = {
    "The Siren": (62, 69),
    "The Witch": (60, 67),
    "The Viper": (62, 68),
    "The Prodigy": (59, 65),
    "The Doll": (59, 64),
    "The Huntress": (65, 71),
    "The Empress": (65, 70),
    "The Experiment": (60, 69),
    "The Demon": (62, 69),
    "The Assassin": (61, 67),
    "The Nymph": (58, 66),
}

ARCHETYPE_BODY_WEIGHTS = {
    "The Siren": {
        "breast_size": {
            "tiny flat-chested": 2,
            "small perky": 7,
            "medium": 23,
            "large heavy": 50,
            "massive oversized": 18,
        },
        "body_fat_pct": {
            "lean 12-16%": 5,
            "athletic 17-20%": 32,
            "fit 21-24%": 53,
            "soft 25-30%": 10,
        },
        "makeup_level": {
            "bare-faced": 3,
            "light": 35,
            "moderate": 47,
            "heavy": 15,
        },
        "abs_tone": {
            "soft with no definition": 22,
            "slight definition": 48,
            "toned and defined": 28,
            "ripped and shredded": 2,
        },
        "butt_size": {
            "tiny tight": 18,
            "medium round": 43,
            "large thick": 33,
            "very large prominent": 6,
        },
        "waist": {"narrow": 40, "medium": 45, "wide": 15},
        "eye_expression": {
            "half-lidded": 25, "smoldering": 25, "knowing": 20, "contemptuous": 15,
            "cold": 5, "piercing": 5, "heavy-lidded": 5,
        },
    },
    "The Witch": {
        "breast_size": {
            "tiny flat-chested": 9,
            "small perky": 22,
            "medium": 34,
            "large heavy": 27,
            "massive oversized": 8,
        },
        "body_fat_pct": {
            "lean 12-16%": 11,
            "athletic 17-20%": 35,
            "fit 21-24%": 40,
            "soft 25-30%": 14,
        },
        "makeup_level": {
            "bare-faced": 5,
            "light": 35,
            "moderate": 42,
            "heavy": 18,
        },
        "abs_tone": {
            "soft with no definition": 32,
            "slight definition": 42,
            "toned and defined": 24,
            "ripped and shredded": 2,
        },
        "butt_size": {
            "tiny tight": 22,
            "medium round": 42,
            "large thick": 32,
            "very large prominent": 4,
        },
        "waist": {"narrow": 35, "medium": 45, "wide": 20},
        "eye_expression": {
            "piercing": 25, "knowing": 20, "vacant": 20, "unblinking": 20,
            "cold": 10, "half-lidded": 5,
        },
    },
    "The Viper": {
        "breast_size": {
            "tiny flat-chested": 10,
            "small perky": 26,
            "medium": 38,
            "large heavy": 23,
            "massive oversized": 3,
        },
        "body_fat_pct": {
            "lean 12-16%": 16,
            "athletic 17-20%": 47,
            "fit 21-24%": 34,
            "soft 25-30%": 3,
        },
        "makeup_level": {
            "bare-faced": 10,
            "light": 35,
            "moderate": 40,
            "heavy": 15,
        },
        "abs_tone": {
            "soft with no definition": 8,
            "slight definition": 30,
            "toned and defined": 52,
            "ripped and shredded": 10,
        },
        "butt_size": {
            "tiny tight": 26,
            "medium round": 47,
            "large thick": 25,
            "very large prominent": 2,
        },
        "waist": {"narrow": 50, "medium": 40, "wide": 10},
        "eye_expression": {
            "narrowed": 25, "calculating": 25, "cold": 20, "knowing": 15,
            "piercing": 10, "contemptuous": 5,
        },
    },
    "The Prodigy": {
        "breast_size": {
            "tiny flat-chested": 15,
            "small perky": 33,
            "medium": 33,
            "large heavy": 17,
            "massive oversized": 2,
        },
        "body_fat_pct": {
            "lean 12-16%": 21,
            "athletic 17-20%": 50,
            "fit 21-24%": 26,
            "soft 25-30%": 3,
        },
        "makeup_level": {
            "bare-faced": 25,
            "light": 40,
            "moderate": 30,
            "heavy": 5,
        },
        "abs_tone": {
            "soft with no definition": 8,
            "slight definition": 22,
            "toned and defined": 58,
            "ripped and shredded": 12,
        },
        "butt_size": {
            "tiny tight": 36,
            "medium round": 41,
            "large thick": 21,
            "very large prominent": 2,
        },
        "waist": {"narrow": 45, "medium": 45, "wide": 10},
        "eye_expression": {
            "focused": 30, "fierce": 25, "calculating": 20, "piercing": 15,
            "narrowed": 10,
        },
    },
    "The Doll": {
        "breast_size": {
            "tiny flat-chested": 12,
            "small perky": 29,
            "medium": 31,
            "large heavy": 23,
            "massive oversized": 5,
        },
        "body_fat_pct": {
            "lean 12-16%": 11,
            "athletic 17-20%": 32,
            "fit 21-24%": 47,
            "soft 25-30%": 10,
        },
        "makeup_level": {
            "bare-faced": 8,
            "light": 37,
            "moderate": 42,
            "heavy": 13,
        },
        "abs_tone": {
            "soft with no definition": 27,
            "slight definition": 43,
            "toned and defined": 28,
            "ripped and shredded": 2,
        },
        "butt_size": {
            "tiny tight": 22,
            "medium round": 42,
            "large thick": 32,
            "very large prominent": 4,
        },
        "waist": {"narrow": 45, "medium": 40, "wide": 15},
        "eye_expression": {
            "wide unblinking": 30, "vacant": 25, "unblinking": 20,
            "knowing": 15, "cold": 10,
        },
    },
    "The Huntress": {
        "breast_size": {
            "tiny flat-chested": 8,
            "small perky": 21,
            "medium": 38,
            "large heavy": 28,
            "massive oversized": 5,
        },
        "body_fat_pct": {
            "lean 12-16%": 19,
            "athletic 17-20%": 49,
            "fit 21-24%": 29,
            "soft 25-30%": 3,
        },
        "makeup_level": {
            "bare-faced": 20,
            "light": 40,
            "moderate": 32,
            "heavy": 8,
        },
        "abs_tone": {
            "soft with no definition": 8,
            "slight definition": 25,
            "toned and defined": 52,
            "ripped and shredded": 15,
        },
        "butt_size": {
            "tiny tight": 27,
            "medium round": 42,
            "large thick": 27,
            "very large prominent": 4,
        },
        "waist": {"narrow": 35, "medium": 50, "wide": 15},
        "eye_expression": {
            "predatory": 25, "narrowed": 25, "fierce": 20, "focused": 15,
            "piercing": 10, "glaring": 5,
        },
    },
    "The Empress": {
        "breast_size": {
            "tiny flat-chested": 2,
            "small perky": 7,
            "medium": 26,
            "large heavy": 47,
            "massive oversized": 18,
        },
        "body_fat_pct": {
            "lean 12-16%": 6,
            "athletic 17-20%": 28,
            "fit 21-24%": 50,
            "soft 25-30%": 16,
        },
        "makeup_level": {
            "bare-faced": 3,
            "light": 32,
            "moderate": 47,
            "heavy": 18,
        },
        "abs_tone": {
            "soft with no definition": 27,
            "slight definition": 43,
            "toned and defined": 28,
            "ripped and shredded": 2,
        },
        "butt_size": {
            "tiny tight": 18,
            "medium round": 43,
            "large thick": 33,
            "very large prominent": 6,
        },
        "waist": {"narrow": 25, "medium": 45, "wide": 30},
        "eye_expression": {
            "contemptuous": 30, "cold": 25, "half-lidded": 20, "piercing": 15,
            "knowing": 10,
        },
    },
    "The Experiment": {
        "breast_size": {
            "tiny flat-chested": 8,
            "small perky": 20,
            "medium": 30,
            "large heavy": 30,
            "massive oversized": 12,
        },
        "body_fat_pct": {
            "lean 12-16%": 14,
            "athletic 17-20%": 44,
            "fit 21-24%": 34,
            "soft 25-30%": 8,
        },
        "makeup_level": {
            "bare-faced": 12,
            "light": 37,
            "moderate": 38,
            "heavy": 13,
        },
        "abs_tone": {
            "soft with no definition": 15,
            "slight definition": 30,
            "toned and defined": 43,
            "ripped and shredded": 12,
        },
        "butt_size": {
            "tiny tight": 28,
            "medium round": 42,
            "large thick": 22,
            "very large prominent": 8,
        },
        "waist": {"narrow": 30, "medium": 45, "wide": 25},
        "eye_expression": {
            "vacant": 25, "unblinking": 25, "cold": 20, "piercing": 15,
            "wide unblinking": 10, "calculating": 5,
        },
    },
    "The Demon": {
        "breast_size": {
            "tiny flat-chested": 4,
            "small perky": 10,
            "medium": 24,
            "large heavy": 44,
            "massive oversized": 18,
        },
        "body_fat_pct": {
            "lean 12-16%": 8,
            "athletic 17-20%": 30,
            "fit 21-24%": 50,
            "soft 25-30%": 12,
        },
        "makeup_level": {
            "bare-faced": 3,
            "light": 12,
            "moderate": 40,
            "heavy": 45,
        },
        "abs_tone": {
            "soft with no definition": 20,
            "slight definition": 45,
            "toned and defined": 30,
            "ripped and shredded": 5,
        },
        "butt_size": {
            "tiny tight": 9,
            "medium round": 31,
            "large thick": 48,
            "very large prominent": 12,
        },
        "waist": {"narrow": 35, "medium": 45, "wide": 20},
        "eye_expression": {
            "smoldering": 25, "predatory": 25, "wild": 20, "half-lidded": 15,
            "piercing": 10, "heavy-lidded": 5,
        },
    },
    "The Assassin": {
        "breast_size": {
            "tiny flat-chested": 15,
            "small perky": 35,
            "medium": 33,
            "large heavy": 15,
            "massive oversized": 2,
        },
        "body_fat_pct": {
            "lean 12-16%": 35,
            "athletic 17-20%": 46,
            "fit 21-24%": 18,
            "soft 25-30%": 1,
        },
        "makeup_level": {
            "bare-faced": 35,
            "light": 40,
            "moderate": 20,
            "heavy": 5,
        },
        "abs_tone": {
            "soft with no definition": 3,
            "slight definition": 15,
            "toned and defined": 52,
            "ripped and shredded": 30,
        },
        "butt_size": {
            "tiny tight": 31,
            "medium round": 44,
            "large thick": 23,
            "very large prominent": 2,
        },
        "waist": {"narrow": 50, "medium": 40, "wide": 10},
        "eye_expression": {
            "cold": 25, "narrowed": 25, "calculating": 20, "focused": 15,
            "piercing": 10, "glaring": 5,
        },
    },
    "The Nymph": {
        "breast_size": {
            "tiny flat-chested": 10,
            "small perky": 31,
            "medium": 36,
            "large heavy": 19,
            "massive oversized": 4,
        },
        "body_fat_pct": {
            "lean 12-16%": 12,
            "athletic 17-20%": 34,
            "fit 21-24%": 44,
            "soft 25-30%": 10,
        },
        "makeup_level": {
            "bare-faced": 30,
            "light": 45,
            "moderate": 20,
            "heavy": 5,
        },
        "abs_tone": {
            "soft with no definition": 25,
            "slight definition": 45,
            "toned and defined": 25,
            "ripped and shredded": 5,
        },
        "butt_size": {
            "tiny tight": 17,
            "medium round": 43,
            "large thick": 35,
            "very large prominent": 5,
        },
        "waist": {"narrow": 45, "medium": 40, "wide": 15},
        "eye_expression": {
            "knowing": 25, "wild": 20, "half-lidded": 20, "piercing": 15,
            "smoldering": 10, "unblinking": 10,
        },
    },
}
